// 甲子園 春夏内訳データ
// 出典・取得時点はREADME.mdの「甲子園パワーランキングのデータ出典」を参照
// 合計(出場・優勝・勝利)はここには持たず、koshien-ranking.html側で春+夏から毎回計算する
const KOSHIEN_SCHOOLS = [
  {
    name: "大阪桐蔭",
    pref: "大阪府",
    spring: { appearances: 16, championships: 5, wins: 41 },
    summer: { appearances: 13, championships: 5, wins: 42 },
  },
  {
    name: "智辯和歌山",
    pref: "和歌山県",
    spring: { appearances: 16, championships: 1, wins: 31 },
    summer: { appearances: 29, championships: 3, wins: 47 },
  },
  {
    name: "横浜",
    pref: "神奈川県",
    spring: { appearances: 18, championships: 4, wins: 28 },
    summer: { appearances: 22, championships: 2, wins: 44 },
  },
  {
    name: "東海大相模",
    pref: "神奈川県",
    spring: { appearances: 12, championships: 3, wins: 28 },
    summer: { appearances: 12, championships: 2, wins: 21 },
  },
  {
    name: "慶應義塾",
    pref: "神奈川県",
    spring: { appearances: 11, championships: 0, wins: 5 },
    summer: { appearances: 19, championships: 2, wins: 20 },
  },
  {
    name: "中京大中京",
    pref: "愛知県",
    spring: { appearances: 33, championships: 4, wins: 61 },
    summer: { appearances: 29, championships: 7, wins: 79 },
  },
  {
    name: "東邦",
    pref: "愛知県",
    spring: { appearances: 31, championships: 5, wins: 58 },
    summer: { appearances: 17, championships: 0, wins: 19 },
  },
  {
    name: "龍谷大平安",
    pref: "京都府",
    spring: { appearances: 42, championships: 1, wins: 43 },
    summer: { appearances: 34, championships: 3, wins: 61 },
  },
  {
    name: "仙台育英",
    pref: "宮城県",
    spring: { appearances: 15, championships: 0, wins: 16 },
    summer: { appearances: 32, championships: 1, wins: 51 },
  },
  {
    name: "履正社",
    pref: "大阪府",
    spring: { appearances: 10, championships: 0, wins: 13 },
    summer: { appearances: 6, championships: 1, wins: 12 },
  },
  {
    name: "広陵",
    pref: "広島県",
    spring: { appearances: 27, championships: 3, wins: 43 },
    summer: { appearances: 26, championships: 0, wins: 37 },
  },
  {
    name: "明徳義塾",
    pref: "高知県",
    spring: { appearances: 21, championships: 0, wins: 25 },
    summer: { appearances: 24, championships: 1, wins: 38 },
  },
  {
    name: "帝京",
    pref: "東京都",
    spring: { appearances: 15, championships: 1, wins: 22 },
    summer: { appearances: 12, championships: 2, wins: 30 },
  },
  {
    name: "日大三",
    pref: "東京都",
    spring: { appearances: 20, championships: 1, wins: 27 },
    summer: { appearances: 20, championships: 2, wins: 33 },
  },
  {
    name: "花巻東",
    pref: "岩手県",
    spring: { appearances: 6, championships: 0, wins: 8 },
    summer: { appearances: 14, championships: 0, wins: 17 },
  },
  {
    name: "花咲徳栄",
    pref: "埼玉県",
    spring: { appearances: 6, championships: 0, wins: 5 },
    summer: { appearances: 9, championships: 1, wins: 12 },
  },
  {
    name: "報徳学園",
    pref: "兵庫県",
    spring: { appearances: 23, championships: 2, wins: 40 },
    summer: { appearances: 16, championships: 1, wins: 28 },
  },
  {
    name: "智辯学園",
    pref: "奈良県",
    spring: { appearances: 15, championships: 1, wins: 20 },
    summer: { appearances: 22, championships: 0, wins: 31 },
  },
  {
    name: "神村学園",
    pref: "鹿児島県",
    spring: { appearances: 7, championships: 0, wins: 8 },
    summer: { appearances: 9, championships: 0, wins: 13 },
  },
  {
    name: "山梨学院",
    pref: "山梨県",
    spring: { appearances: 9, championships: 1, wins: 13 },
    summer: { appearances: 11, championships: 0, wins: 5 },
  },
  {
    name: "東洋大姫路",
    pref: "兵庫県",
    spring: { appearances: 10, championships: 0, wins: 14 },
    summer: { appearances: 13, championships: 1, wins: 23 },
  },
  {
    name: "沖縄尚学",
    pref: "沖縄県",
    spring: { appearances: 9, championships: 2, wins: 17 },
    summer: { appearances: 12, championships: 1, wins: 16 },
  },
  {
    name: "佐野日大",
    pref: "栃木県",
    spring: { appearances: 5, championships: 0, wins: 5 },
    summer: { appearances: 7, championships: 0, wins: 6 },
  },
  {
    name: "健大高崎",
    pref: "群馬県",
    spring: { appearances: 8, championships: 1, wins: 16 },
    summer: { appearances: 6, championships: 0, wins: 12 },
  },
  {
    name: "京都国際",
    pref: "京都府",
    spring: { appearances: 2, championships: 0, wins: 1 },
    summer: { appearances: 4, championships: 1, wins: 11 },
  },
  {
    name: "聖光学院",
    pref: "福島県",
    spring: { appearances: 7, championships: 0, wins: 7 },
    summer: { appearances: 20, championships: 0, wins: 24 },
  },
  {
    name: "青森山田",
    pref: "青森県",
    spring: { appearances: 4, championships: 0, wins: 2 },
    summer: { appearances: 13, championships: 0, wins: 16 },
  },
  {
    name: "早稲田実業",
    pref: "東京都",
    spring: { appearances: 22, championships: 1, wins: 24 },
    summer: { appearances: 30, championships: 1, wins: 45 },
  },
  {
    name: "関東第一",
    pref: "東京都",
    spring: { appearances: 7, championships: 0, wins: 8 },
    summer: { appearances: 11, championships: 0, wins: 20 },
  },
  {
    name: "明豊",
    pref: "大分県",
    spring: { appearances: 6, championships: 0, wins: 9 },
    summer: { appearances: 11, championships: 0, wins: 13 },
  },
  {
    name: "鶴岡東",
    pref: "山形県",
    spring: { appearances: 2, championships: 0, wins: 1 },
    summer: { appearances: 9, championships: 0, wins: 5 },
  },
  {
    name: "東海大菅生",
    pref: "東京都",
    spring: { appearances: 5, championships: 0, wins: 4 },
    summer: { appearances: 4, championships: 0, wins: 4 },
  },
  {
    name: "済美",
    pref: "愛媛県",
    spring: { appearances: 2, championships: 1, wins: 9 },
    summer: { appearances: 7, championships: 0, wins: 12 },
  },
  {
    name: "広島商",
    pref: "広島県",
    spring: { appearances: 23, championships: 1, wins: 22 },
    summer: { appearances: 23, championships: 6, wins: 43 },
  },
  {
    name: "松山商業",
    pref: "愛媛県",
    spring: { appearances: 16, championships: 2, wins: 20 },
    summer: { appearances: 26, championships: 5, wins: 60 },
  },
  {
    name: "浦和学院",
    pref: "埼玉県",
    spring: { appearances: 11, championships: 1, wins: 23 },
    summer: { appearances: 15, championships: 0, wins: 12 },
  },
  {
    name: "常総学院",
    pref: "茨城県",
    spring: { appearances: 11, championships: 1, wins: 15 },
    summer: { appearances: 16, championships: 1, wins: 28 },
  },
  {
    name: "天理",
    pref: "奈良県",
    spring: { appearances: 27, championships: 1, wins: 30 },
    summer: { appearances: 31, championships: 2, wins: 52 },
  },
  {
    name: "敦賀気比",
    pref: "福井県",
    spring: { appearances: 12, championships: 1, wins: 14 },
    summer: { appearances: 13, championships: 0, wins: 19 },
  },
  {
    name: "作新学院",
    pref: "栃木県",
    spring: { appearances: 12, championships: 1, wins: 14 },
    summer: { appearances: 16, championships: 2, wins: 27 },
  },
  {
    name: "高松商業",
    pref: "香川県",
    spring: { appearances: 29, championships: 2, wins: 37 },
    summer: { appearances: 22, championships: 2, wins: 25 },
  },
  {
    name: "桐蔭学園",
    pref: "神奈川県",
    spring: { appearances: 6, championships: 0, wins: 4 },
    summer: { appearances: 6, championships: 1, wins: 12 },
  },
  {
    name: "大体大浪商",
    pref: "大阪府",
    spring: { appearances: 19, championships: 2, wins: 32 },
    summer: { appearances: 13, championships: 2, wins: 17 },
  },
  {
    name: "秋田商業",
    pref: "秋田県",
    spring: { appearances: 6, championships: 0, wins: 8 },
    summer: { appearances: 18, championships: 0, wins: 10 },
  },
  {
    name: "銚子商業",
    pref: "千葉県",
    spring: { appearances: 8, championships: 0, wins: 14 },
    summer: { appearances: 12, championships: 1, wins: 25 },
  },
  {
    name: "静岡商業",
    pref: "静岡県",
    spring: { appearances: 6, championships: 1, wins: 6 },
    summer: { appearances: 9, championships: 0, wins: 17 },
  },
  {
    name: "県岐阜商",
    pref: "岐阜県",
    spring: { appearances: 30, championships: 3, wins: 48 },
    summer: { appearances: 31, championships: 1, wins: 43 },
  },
  {
    name: "倉敷商",
    pref: "岡山県",
    spring: { appearances: 4, championships: 0, wins: 0 },
    summer: { appearances: 11, championships: 0, wins: 8 },
  },
  {
    name: "二松学舎大付",
    pref: "東京都",
    spring: { appearances: 8, championships: 0, wins: 5 },
    summer: { appearances: 5, championships: 0, wins: 6 },
  },
  {
    name: "佐賀北",
    pref: "佐賀県",
    spring: { appearances: 0, championships: 0, wins: 0 },
    summer: { appearances: 6, championships: 1, wins: 7 },
  },
  {
    name: "高知商業",
    pref: "高知県",
    spring: { appearances: 14, championships: 1, wins: 23 },
    summer: { appearances: 23, championships: 0, wins: 38 },
  },
  {
    name: "沖縄水産",
    pref: "沖縄県",
    spring: { appearances: 3, championships: 0, wins: 1 },
    summer: { appearances: 9, championships: 0, wins: 20 },
  },
  {
    name: "八戸学院光星",
    pref: "青森県",
    spring: { appearances: 12, championships: 0, wins: 11 },
    summer: { appearances: 12, championships: 0, wins: 26 },
  },
  {
    name: "習志野",
    pref: "千葉県",
    spring: { appearances: 4, championships: 0, wins: 6 },
    summer: { appearances: 9, championships: 2, wins: 20 },
  },
  {
    name: "済々黌",
    pref: "熊本県",
    spring: { appearances: 4, championships: 1, wins: 8 },
    summer: { appearances: 7, championships: 0, wins: 8 },
  },
  {
    name: "東北",
    pref: "宮城県",
    spring: { appearances: 21, championships: 0, wins: 15 },
    summer: { appearances: 22, championships: 0, wins: 28 },
  },
  {
    name: "尽誠学園",
    pref: "香川県",
    spring: { appearances: 7, championships: 0, wins: 4 },
    summer: { appearances: 12, championships: 0, wins: 14 },
  },
  {
    name: "佐賀商業",
    pref: "佐賀県",
    spring: { appearances: 6, championships: 0, wins: 4 },
    summer: { appearances: 17, championships: 1, wins: 13 },
  },
  {
    name: "中央学院",
    pref: "千葉県",
    spring: { appearances: 2, championships: 0, wins: 3 },
    summer: { appearances: 1, championships: 0, wins: 0 },
  },
  {
    name: "三重",
    pref: "三重県",
    spring: { appearances: 14, championships: 1, wins: 17 },
    summer: { appearances: 15, championships: 0, wins: 15 },
  },
  {
    name: "熊本工業",
    pref: "熊本県",
    spring: { appearances: 22, championships: 0, wins: 16 },
    summer: { appearances: 23, championships: 0, wins: 30 },
  },
  {
    name: "桜美林",
    pref: "東京都",
    spring: { appearances: 6, championships: 0, wins: 3 },
    summer: { appearances: 4, championships: 1, wins: 8 },
  },
  {
    name: "日大山形",
    pref: "山形県",
    spring: { appearances: 4, championships: 0, wins: 3 },
    summer: { appearances: 20, championships: 0, wins: 14 },
  },
  {
    name: "宇部商業",
    pref: "山口県",
    spring: { appearances: 7, championships: 0, wins: 8 },
    summer: { appearances: 12, championships: 0, wins: 19 },
  },
  {
    name: "駒大苫小牧",
    pref: "北海道",
    spring: { appearances: 4, championships: 0, wins: 2 },
    summer: { appearances: 7, championships: 2, wins: 14 },
  },
  {
    name: "星稜",
    pref: "石川県",
    spring: { appearances: 16, championships: 0, wins: 14 },
    summer: { appearances: 22, championships: 0, wins: 24 },
  },
  {
    name: "前橋育英",
    pref: "群馬県",
    spring: { appearances: 2, championships: 0, wins: 1 },
    summer: { appearances: 6, championships: 1, wins: 9 },
  },
  {
    name: "常葉大菊川",
    pref: "静岡県",
    spring: { appearances: 6, championships: 1, wins: 8 },
    summer: { appearances: 6, championships: 0, wins: 10 },
  },
  {
    name: "秀岳館",
    pref: "熊本県",
    spring: { appearances: 3, championships: 0, wins: 6 },
    summer: { appearances: 3, championships: 0, wins: 5 },
  },
  {
    name: "木更津総合",
    pref: "千葉県",
    spring: { appearances: 4, championships: 0, wins: 7 },
    summer: { appearances: 8, championships: 0, wins: 8 },
  },
  {
    name: "東海大甲府",
    pref: "山梨県",
    spring: { appearances: 6, championships: 0, wins: 8 },
    summer: { appearances: 15, championships: 0, wins: 21 },
  },
  {
    name: "松商学園",
    pref: "長野県",
    spring: { appearances: 16, championships: 0, wins: 13 },
    summer: { appearances: 39, championships: 1, wins: 28 },
  },
  {
    name: "帯広農業",
    pref: "北海道",
    spring: { appearances: 1, championships: 0, wins: 0 },
    summer: { appearances: 2, championships: 0, wins: 0 },
  },
  {
    name: "岡山理大付",
    pref: "岡山県",
    spring: { appearances: 5, championships: 0, wins: 1 },
    summer: { appearances: 5, championships: 0, wins: 6 },
  },
  {
    name: "大分商業",
    pref: "大分県",
    spring: { appearances: 7, championships: 0, wins: 4 },
    summer: { appearances: 16, championships: 0, wins: 13 },
  },
  {
    name: "高知",
    pref: "高知県",
    spring: { appearances: 21, championships: 1, wins: 21 },
    summer: { appearances: 13, championships: 1, wins: 16 },
  },
  {
    name: "鹿児島実業",
    pref: "鹿児島県",
    spring: { appearances: 9, championships: 1, wins: 15 },
    summer: { appearances: 20, championships: 0, wins: 18 },
  },
  {
    name: "樟南",
    pref: "鹿児島県",
    spring: { appearances: 7, championships: 0, wins: 4 },
    summer: { appearances: 20, championships: 0, wins: 24 },
  },
  {
    name: "浜松商業",
    pref: "静岡県",
    spring: { appearances: 8, championships: 1, wins: 10 },
    summer: { appearances: 9, championships: 0, wins: 11 },
  },
  {
    name: "金足農",
    pref: "秋田県",
    spring: { appearances: 3, championships: 0, wins: 1 },
    summer: { appearances: 8, championships: 0, wins: 12 },
  },
  {
    name: "宇和島東",
    pref: "愛媛県",
    spring: { appearances: 4, championships: 1, wins: 7 },
    summer: { appearances: 9, championships: 0, wins: 3 },
  },
  {
    name: "今治西",
    pref: "愛媛県",
    spring: { appearances: 14, championships: 0, wins: 14 },
    summer: { appearances: 13, championships: 0, wins: 20 },
  },
  {
    name: "鳥取城北",
    pref: "鳥取県",
    spring: { appearances: 4, championships: 0, wins: 1 },
    summer: { appearances: 8, championships: 0, wins: 1 },
  },
  {
    name: "創成館",
    pref: "長崎県",
    spring: { appearances: 4, championships: 0, wins: 2 },
    summer: { appearances: 5, championships: 0, wins: 5 },
  },
  {
    name: "長崎日大",
    pref: "長崎県",
    spring: { appearances: 5, championships: 0, wins: 2 },
    summer: { appearances: 10, championships: 0, wins: 11 },
  },
  {
    name: "国士舘",
    pref: "東京都",
    spring: { appearances: 10, championships: 0, wins: 9 },
    summer: { appearances: 1, championships: 0, wins: 1 },
  },
  {
    name: "上宮",
    pref: "大阪府",
    spring: { appearances: 8, championships: 1, wins: 19 },
    summer: { appearances: 1, championships: 0, wins: 3 },
  },
  {
    name: "近大付",
    pref: "大阪府",
    spring: { appearances: 7, championships: 1, wins: 10 },
    summer: { appearances: 5, championships: 0, wins: 2 },
  },
  {
    name: "明桜",
    pref: "秋田県",
    spring: { appearances: 5, championships: 0, wins: 2 },
    summer: { appearances: 11, championships: 0, wins: 7 },
  },
  {
    name: "高崎商業",
    pref: "群馬県",
    spring: { appearances: 3, championships: 0, wins: 0 },
    summer: { appearances: 11, championships: 0, wins: 5 },
  },
  {
    name: "徳島商業",
    pref: "徳島県",
    spring: { appearances: 19, championships: 1, wins: 20 },
    summer: { appearances: 24, championships: 0, wins: 22 },
  },
  {
    name: "崇徳",
    pref: "広島県",
    spring: { appearances: 4, championships: 1, wins: 5 },
    summer: { appearances: 2, championships: 0, wins: 3 },
  },
  {
    name: "呉港",
    pref: "広島県",
    spring: { appearances: 5, championships: 0, wins: 3 },
    summer: { appearances: 6, championships: 1, wins: 11 },
  },
  {
    name: "高川学園",
    pref: "山口県",
    spring: { appearances: 2, championships: 0, wins: 0 },
    summer: { appearances: 4, championships: 0, wins: 3 },
  },
  {
    name: "佐久長聖",
    pref: "長野県",
    spring: { appearances: 1, championships: 0, wins: 0 },
    summer: { appearances: 9, championships: 0, wins: 7 },
  },
  {
    name: "福井商業",
    pref: "福井県",
    spring: { appearances: 17, championships: 0, wins: 14 },
    summer: { appearances: 22, championships: 0, wins: 19 },
  },
  {
    name: "富山商業",
    pref: "富山県",
    spring: { appearances: 6, championships: 0, wins: 2 },
    summer: { appearances: 18, championships: 0, wins: 8 },
  },
  {
    name: "小松大谷",
    pref: "石川県",
    spring: { appearances: 0, championships: 0, wins: 0 },
    summer: { appearances: 4, championships: 0, wins: 2 },
  },
  {
    name: "日本航空石川",
    pref: "石川県",
    spring: { appearances: 4, championships: 0, wins: 2 },
    summer: { appearances: 2, championships: 0, wins: 2 },
  },
  {
    name: "新潟明訓",
    pref: "新潟県",
    spring: { appearances: 1, championships: 0, wins: 0 },
    summer: { appearances: 7, championships: 0, wins: 7 },
  },
  {
    name: "日本文理",
    pref: "新潟県",
    spring: { appearances: 6, championships: 0, wins: 4 },
    summer: { appearances: 13, championships: 0, wins: 9 },
  },
  {
    name: "帝京長岡",
    pref: "新潟県",
    spring: { appearances: 1, championships: 0, wins: 0 },
    summer: { appearances: 1, championships: 0, wins: 0 },
  },
  {
    name: "近江",
    pref: "滋賀県",
    spring: { appearances: 8, championships: 0, wins: 9 },
    summer: { appearances: 17, championships: 0, wins: 20 },
  },
  {
    name: "滋賀学園",
    pref: "滋賀県",
    spring: { appearances: 4, championships: 0, wins: 4 },
    summer: { appearances: 2, championships: 0, wins: 3 },
  },
  {
    name: "箕島",
    pref: "和歌山県",
    spring: { appearances: 9, championships: 3, wins: 24 },
    summer: { appearances: 8, championships: 1, wins: 13 },
  },
  {
    name: "市和歌山",
    pref: "和歌山県",
    spring: { appearances: 9, championships: 0, wins: 11 },
    summer: { appearances: 6, championships: 0, wins: 6 },
  },
  {
    name: "佐賀学園",
    pref: "佐賀県",
    spring: { appearances: 0, championships: 0, wins: 0 },
    summer: { appearances: 6, championships: 0, wins: 6 },
  },
  {
    name: "有田工",
    pref: "佐賀県",
    spring: { appearances: 1, championships: 0, wins: 0 },
    summer: { appearances: 3, championships: 0, wins: 1 },
  },
  {
    name: "池田",
    pref: "徳島県",
    spring: { appearances: 8, championships: 2, wins: 22 },
    summer: { appearances: 9, championships: 1, wins: 20 },
  },
  {
    name: "鳴門",
    pref: "徳島県",
    spring: { appearances: 9, championships: 1, wins: 15 },
    summer: { appearances: 15, championships: 0, wins: 14 },
  },
  {
    name: "松山東",
    pref: "愛媛県",
    spring: { appearances: 2, championships: 0, wins: 1 },
    summer: { appearances: 1, championships: 0, wins: 2 },
  },
  {
    name: "三本松",
    pref: "香川県",
    spring: { appearances: 1, championships: 0, wins: 0 },
    summer: { appearances: 3, championships: 0, wins: 2 },
  },
  {
    name: "倉敷工業",
    pref: "岡山県",
    spring: { appearances: 11, championships: 0, wins: 11 },
    summer: { appearances: 9, championships: 0, wins: 14 },
  },
  {
    name: "関西",
    pref: "岡山県",
    spring: { appearances: 12, championships: 0, wins: 11 },
    summer: { appearances: 9, championships: 0, wins: 11 },
  },
  {
    name: "岡山東商業",
    pref: "岡山県",
    spring: { appearances: 8, championships: 1, wins: 6 },
    summer: { appearances: 11, championships: 0, wins: 11 },
  },
  {
    name: "広島工業",
    pref: "広島県",
    spring: { appearances: 5, championships: 0, wins: 6 },
    summer: { appearances: 5, championships: 0, wins: 6 },
  },
  {
    name: "如水館",
    pref: "広島県",
    spring: { appearances: 1, championships: 0, wins: 1 },
    summer: { appearances: 7, championships: 0, wins: 5 },
  },
  {
    name: "岩国",
    pref: "山口県",
    spring: { appearances: 7, championships: 0, wins: 0 },
    summer: { appearances: 5, championships: 0, wins: 4 },
  },
  {
    name: "下関商業",
    pref: "山口県",
    spring: { appearances: 14, championships: 1, wins: 13 },
    summer: { appearances: 9, championships: 0, wins: 16 },
  },
  {
    name: "米子東",
    pref: "鳥取県",
    spring: { appearances: 9, championships: 0, wins: 9 },
    summer: { appearances: 15, championships: 0, wins: 8 },
  },
  {
    name: "松江商業",
    pref: "島根県",
    spring: { appearances: 7, championships: 0, wins: 5 },
    summer: { appearances: 3, championships: 0, wins: 2 },
  },
  {
    name: "北照",
    pref: "北海道",
    spring: { appearances: 6, championships: 0, wins: 5 },
    summer: { appearances: 5, championships: 0, wins: 0 },
  },
  {
    name: "弘前学院聖愛",
    pref: "青森県",
    spring: { appearances: 0, championships: 0, wins: 0 },
    summer: { appearances: 3, championships: 0, wins: 2 },
  },
  {
    name: "盛岡大付",
    pref: "岩手県",
    spring: { appearances: 5, championships: 0, wins: 4 },
    summer: { appearances: 11, championships: 0, wins: 8 },
  },
  {
    name: "一関学院",
    pref: "岩手県",
    spring: { appearances: 2, championships: 0, wins: 0 },
    summer: { appearances: 7, championships: 0, wins: 4 },
  },
  {
    name: "学法石川",
    pref: "福島県",
    spring: { appearances: 4, championships: 0, wins: 1 },
    summer: { appearances: 9, championships: 0, wins: 3 },
  },
  {
    name: "利府",
    pref: "宮城県",
    spring: { appearances: 1, championships: 0, wins: 3 },
    summer: { appearances: 1, championships: 0, wins: 1 },
  },
  {
    name: "秋田中央",
    pref: "秋田県",
    spring: { appearances: 0, championships: 0, wins: 0 },
    summer: { appearances: 5, championships: 0, wins: 3 },
  },
  {
    name: "藤代",
    pref: "茨城県",
    spring: { appearances: 2, championships: 0, wins: 2 },
    summer: { appearances: 3, championships: 0, wins: 1 },
  },
  {
    name: "土浦日大",
    pref: "茨城県",
    spring: { appearances: 2, championships: 0, wins: 1 },
    summer: { appearances: 5, championships: 0, wins: 5 },
  },
  {
    name: "文星芸大付",
    pref: "栃木県",
    spring: { appearances: 2, championships: 0, wins: 4 },
    summer: { appearances: 11, championships: 0, wins: 11 },
  },
  {
    name: "桐生第一",
    pref: "群馬県",
    spring: { appearances: 6, championships: 0, wins: 4 },
    summer: { appearances: 9, championships: 1, wins: 13 },
  },
  {
    name: "春日部共栄",
    pref: "埼玉県",
    spring: { appearances: 3, championships: 0, wins: 3 },
    summer: { appearances: 5, championships: 0, wins: 7 },
  },
  {
    name: "拓大紅陵",
    pref: "千葉県",
    spring: { appearances: 4, championships: 0, wins: 4 },
    summer: { appearances: 6, championships: 0, wins: 7 },
  },
  {
    name: "創価",
    pref: "東京都",
    spring: { appearances: 3, championships: 0, wins: 0 },
    summer: { appearances: 5, championships: 0, wins: 5 },
  },
  {
    name: "横浜商業",
    pref: "神奈川県",
    spring: { appearances: 9, championships: 0, wins: 9 },
    summer: { appearances: 7, championships: 0, wins: 15 },
  },
  {
    name: "桐光学園",
    pref: "神奈川県",
    spring: { appearances: 1, championships: 0, wins: 1 },
    summer: { appearances: 4, championships: 0, wins: 7 },
  },
  {
    name: "中越",
    pref: "新潟県",
    spring: { appearances: 0, championships: 0, wins: 0 },
    summer: { appearances: 12, championships: 0, wins: 2 },
  },
  {
    name: "高岡商業",
    pref: "富山県",
    spring: { appearances: 5, championships: 0, wins: 1 },
    summer: { appearances: 23, championships: 0, wins: 11 },
  },
  {
    name: "金沢",
    pref: "石川県",
    spring: { appearances: 9, championships: 0, wins: 8 },
    summer: { appearances: 13, championships: 0, wins: 7 },
  },
  {
    name: "日本航空",
    pref: "山梨県",
    spring: { appearances: 1, championships: 0, wins: 1 },
    summer: { appearances: 7, championships: 0, wins: 5 },
  },
  {
    name: "大垣日大",
    pref: "岐阜県",
    spring: { appearances: 7, championships: 0, wins: 7 },
    summer: { appearances: 6, championships: 0, wins: 6 },
  },
  {
    name: "静岡",
    pref: "静岡県",
    spring: { appearances: 17, championships: 0, wins: 11 },
    summer: { appearances: 26, championships: 1, wins: 22 },
  },
  {
    name: "愛工大名電",
    pref: "愛知県",
    spring: { appearances: 10, championships: 1, wins: 16 },
    summer: { appearances: 15, championships: 0, wins: 8 },
  },
  {
    name: "白山",
    pref: "三重県",
    spring: { appearances: 0, championships: 0, wins: 0 },
    summer: { appearances: 1, championships: 0, wins: 0 },
  },
  {
    name: "立命館宇治",
    pref: "京都府",
    spring: { appearances: 3, championships: 0, wins: 0 },
    summer: { appearances: 5, championships: 0, wins: 1 },
  },
  {
    name: "育英",
    pref: "兵庫県",
    spring: { appearances: 13, championships: 0, wins: 11 },
    summer: { appearances: 6, championships: 1, wins: 17 },
  },
  {
    name: "神港学園",
    pref: "兵庫県",
    spring: { appearances: 5, championships: 0, wins: 6 },
    summer: { appearances: 3, championships: 0, wins: 2 },
  },
  {
    name: "和歌山東",
    pref: "和歌山県",
    spring: { appearances: 1, championships: 0, wins: 1 },
    summer: { appearances: 0, championships: 0, wins: 0 },
  },
  {
    name: "興国",
    pref: "大阪府",
    spring: { appearances: 5, championships: 0, wins: 1 },
    summer: { appearances: 2, championships: 1, wins: 7 },
  },
  {
    name: "大阪学院大",
    pref: "大阪府",
    spring: { appearances: 1, championships: 0, wins: 2 },
    summer: { appearances: 0, championships: 0, wins: 0 },
  },
  {
    name: "創志学園",
    pref: "岡山県",
    spring: { appearances: 4, championships: 0, wins: 2 },
    summer: { appearances: 3, championships: 0, wins: 1 },
  },
  {
    name: "瀬戸内",
    pref: "広島県",
    spring: { appearances: 3, championships: 0, wins: 1 },
    summer: { appearances: 2, championships: 0, wins: 2 },
  },
  {
    name: "鳴門渦潮",
    pref: "徳島県",
    spring: { appearances: 9, championships: 0, wins: 8 },
    summer: { appearances: 9, championships: 0, wins: 9 },
  },
  {
    name: "英明",
    pref: "香川県",
    spring: { appearances: 4, championships: 0, wins: 3 },
    summer: { appearances: 5, championships: 0, wins: 3 },
  },
  {
    name: "新田",
    pref: "愛媛県",
    spring: { appearances: 2, championships: 0, wins: 4 },
    summer: { appearances: 2, championships: 0, wins: 1 },
  },
  {
    name: "高知中央",
    pref: "高知県",
    spring: { appearances: 0, championships: 0, wins: 0 },
    summer: { appearances: 2, championships: 0, wins: 1 },
  },
  {
    name: "東海大福岡",
    pref: "福岡県",
    spring: { appearances: 3, championships: 0, wins: 3 },
    summer: { appearances: 0, championships: 0, wins: 0 },
  },
  {
    name: "九州国際大付",
    pref: "福岡県",
    spring: { appearances: 4, championships: 0, wins: 7 },
    summer: { appearances: 9, championships: 0, wins: 6 },
  },
  {
    name: "西日本短大付",
    pref: "福岡県",
    spring: { appearances: 2, championships: 0, wins: 2 },
    summer: { appearances: 8, championships: 1, wins: 13 },
  },
  {
    name: "清峰",
    pref: "長崎県",
    spring: { appearances: 2, championships: 1, wins: 9 },
    summer: { appearances: 3, championships: 0, wins: 4 },
  },
  {
    name: "九州学院",
    pref: "熊本県",
    spring: { appearances: 6, championships: 0, wins: 5 },
    summer: { appearances: 9, championships: 0, wins: 9 },
  },
  {
    name: "折尾愛真",
    pref: "福岡県",
    spring: { appearances: 0, championships: 0, wins: 0 },
    summer: { appearances: 1, championships: 0, wins: 0 },
  },
  {
    name: "龍谷(佐賀)",
    pref: "佐賀県",
    spring: { appearances: 1, championships: 0, wins: 2 },
    summer: { appearances: 3, championships: 0, wins: 0 },
  },
  {
    name: "柳ヶ浦",
    pref: "大分県",
    spring: { appearances: 3, championships: 0, wins: 1 },
    summer: { appearances: 8, championships: 0, wins: 7 },
  },
  {
    name: "興南",
    pref: "沖縄県",
    spring: { appearances: 4, championships: 1, wins: 5 },
    summer: { appearances: 14, championships: 1, wins: 19 },
  },
  {
    name: "福岡大大濠",
    pref: "福岡県",
    spring: { appearances: 5, championships: 0, wins: 4 },
    summer: { appearances: 3, championships: 0, wins: 5 },
  },
  {
    name: "東筑",
    pref: "福岡県",
    spring: { appearances: 3, championships: 0, wins: 0 },
    summer: { appearances: 7, championships: 0, wins: 3 },
  },
  {
    name: "延岡学園",
    pref: "宮崎県",
    spring: { appearances: 3, championships: 0, wins: 0 },
    summer: { appearances: 7, championships: 0, wins: 6 },
  },
  {
    name: "日南学園",
    pref: "宮崎県",
    spring: { appearances: 5, championships: 0, wins: 5 },
    summer: { appearances: 10, championships: 0, wins: 10 },
  },
  {
    name: "鹿児島商業",
    pref: "鹿児島県",
    spring: { appearances: 12, championships: 0, wins: 1 },
    summer: { appearances: 13, championships: 0, wins: 14 },
  },
  {
    name: "鹿児島城西",
    pref: "鹿児島県",
    spring: { appearances: 1, championships: 0, wins: 0 },
    summer: { appearances: 0, championships: 0, wins: 0 },
  },
  {
    name: "豊見城",
    pref: "沖縄県",
    spring: { appearances: 4, championships: 0, wins: 4 },
    summer: { appearances: 3, championships: 0, wins: 6 },
  },
  {
    name: "佐賀西",
    pref: "佐賀県",
    spring: { appearances: 0, championships: 0, wins: 0 },
    summer: { appearances: 7, championships: 0, wins: 1 },
  },
  {
    name: "諫早",
    pref: "長崎県",
    spring: { appearances: 2, championships: 0, wins: 2 },
    summer: { appearances: 2, championships: 0, wins: 0 },
  },
];
